title: Tech Edge Intrepreneur
description: Turning cutting-edge tech into real-world impact—and income.
baseurl: ""
url: "https://nikitakoselev.github.io"
theme: minima
plugins:
  - jekyll-feed
excerpt_separator: "<!--more-->"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false